In [1]:
def xrange(x):
    return iter(range(x))

In [2]:
import numpy as np

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in xrange(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)
    
print(X)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [3]:
# Сигмоида 
def sigmoid(x, deriv = False):
    if(deriv == True):
        return(sigmoid(x) * (1 - sigmoid(x)))
    return(1 / (1 + np.exp(-x)))
    
# набор входных данных
X = np.array([  [0, 0, 1],
                [0, 1, 1],
                [1, 0, 1],
                [1, 1, 1] ])
    
# выходные данные            
y = np.array([[0, 0, 1, 1]]).T

# сделаем случайные числа более определёнными
np.random.seed(1)

# инициализируем веса случайным образом со средним 0
syn0 = 2 * np.random.random((3, 1)) - 1

for iter in xrange(10000):

    # прямое распространение
    l0 = X
    l1 = sigmoid(np.dot(l0, syn0))

    # насколько мы ошиблись?
    l1_error = y - l1

    # перемножим это с наклоном сигмоиды 
    # на основе значений в l1
    l1_delta = l1_error * sigmoid(l1, True) # !!!

    # обновим веса
    syn0 += np.dot(l0.T, l1_delta) # !!!

print("Выходные данные после тренировки:")
np.set_printoptions(suppress=True)
print(l1)

Выходные данные после тренировки:
[[0.00072157]
 [0.00048099]
 [0.99959241]
 [0.99938852]]


In [4]:
x = np.array([[1, 2, 3],
             [3, 2, 1]])
print(x)
print(x.T) # Вспоминаем транспанирование :3


[[1 2 3]
 [3 2 1]]
[[1 3]
 [2 2]
 [3 1]]
